UpYourChanel.Web/Models/Video.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace UpYourChanel.Web.Models
{
    public class Video 
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Link { get; set; }

        public string Description { get; set; }

        public int Likes { get; set; }

        public int Dislikes { get; set; }

        public User User { get; set; }

        public int UserId { get; set; }

        public Category? Category { get; set; }

        public string IFrameSource
        {
            get
            {
                if (this.Link.Contains("youtube"))
                {
                    var regex = new Regex(@"youtu(?:\.be|be\.com)/(?:(.*)v(/|=)|(.*/)?)(?<id>[a-zA-Z0-9-_]+)", RegexOptions.IgnoreCase);
                    var videoId = regex.Match(this.Link).Groups["id"];
                    return $"https://www.youtube.com/embed/{videoId}";
                }
                else
                {
                    return this.Link;
                }
            }
        }
    }
}

UpYourChanel.Web/ViewModels/Video/AllVideosViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace UpYourChannel.Web.ViewModels.Video
{
    public class AllVideosViewModel
    {
        public IQueryable<VideoViewModel> AllVideos { get; set; }

       // [Required]
       // [MinLength(1)]
       // public string Search { get; set; }
    }
}

UpYourChanel.Web/ViewModels/Video/VideoInputModel.cs
using System.ComponentModel.DataAnnotations;

namespace UpYourChannel.Web.ViewModels.Video
{
    public class VideoInputModel
    {
        [Required]
        public string Title { get; set; }

        [Url]
        [Required]
        public string Link { get; set; }

        [Required]
        public string Description { get; set; }
    }
}

UpYourChanel.Web/ViewModels/Video/VideoSearchModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UpYourChannel.Web.ViewModels.Video
{
    public class VideoSearchModel
    {
        public string Name { get; set; }
    }
}

UpYourChanel.Web/ViewModels/Video/VideoViewModel.cs
using System.Text.RegularExpressions;

namespace UpYourChannel.Web.ViewModels.Video
{
    public class VideoViewModel
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Link { get; set; }

        public string Description { get; set; }

        // MAYBE REMOVE UserId
        public string UserId { get; set; }

        public string IFrameSource
        {
            get
            {
                if (this.Link.Contains("youtube"))
                {
                    var regex = new Regex(@"youtu(?:\.be|be\.com)/(?:(.*)v(/|=)|(.*/)?)(?<id>[a-zA-Z0-9-_]+)", RegexOptions.IgnoreCase);
                    var videoId = regex.Match(this.Link).Groups["id"];
                    return $"https://www.youtube.com/embed/{videoId}";
                }
                else
                {
                    return this.Link;
                }
            }
        }
    }
}

UpYourChanel.Web/Areas/Administration/Controllers/VideoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using UpYourChannel.Data.Data;
using UpYourChannel.Data.Models;
using UpYourChannel.Web.Paging;
using UpYourChannel.Web.Services;
using UpYourChannel.Web.ViewModels.Video;

namespace UpYourChannel.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    [Authorize(Roles = GlobalConstants.AdminRoleName)]
    public class VideoController : Controller
    {
        private readonly IVideoService videoService;

        public VideoController(IVideoService videoService)
        {
            this.videoService = videoService;
        }

       //public IActionResult AllVideos()
       //{
       //
       //    return this.View(videoService.AllVideos());
       //}

        public async Task<IActionResult> RemoveVideoById(int id)
        {
            await videoService.RemoveVideoByIdAsync(id);
            return Redirect("/Administration/Video/AllVideos");
        }

        [HttpPost]
        public async Task<IActionResult> EditVideoTitle(int videoId,string newTitle)
        {
            await videoService.EditVideoTitleAsync(videoId, newTitle);
            return Redirect("/Administration/Video/AllVideos");
        }

        public IActionResult AllVideos(string searchString, int? pageNumber)
        {
            ViewData["CurrentFilter"] = searchString;
            var videos = string.IsNullOrEmpty(searchString) ? videoService.AllVideos()
                : videoService.VideosBySearch(searchString);
            return View(PaginatedList<VideoViewModel>.Create(videos.AllVideos, pageNumber ?? 1, GlobalConstants.PageSize));
        }
    }
}

UpYourChanel.Web/Controllers/RequestedVideoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using UpYourChannel.Data.Models;
using UpYourChannel.Web.Services;
using UpYourChannel.Web.ViewModels.Video;

namespace UpYourChannel.Web.Controllers
{
    public class RequestedVideoController : Controller
    {
        private readonly IRequestedVideoService requestedVideoService;
        private readonly UserManager<User> userManager;

        public RequestedVideoController(IRequestedVideoService requestedVideoService, UserManager<User> userManager)
        {
            this.requestedVideoService = requestedVideoService;
            this.userManager = userManager;
        }

        [Authorize]
        public IActionResult AddRequestedVideo()
        {
            return this.View("~/Views/Video/AddVideo.cshtml");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddRequestedVideo(VideoInputModel input)
        {
            if (!ModelState.IsValid)
            {
                return this.View("~/Views/Video/AddVideo.cshtml", input);
            }
            var userId = userManager.GetUserId(User);
            await requestedVideoService.AddRequestedVideoAsync(input.Title, input.Link, input.Description, userId);
            TempData["SuccessOnAddVideo"] = "Thanks for adding your video.";
            return Redirect("/Video/AllVideos");
        }
    }
}

UpYourChanel.Web/Controllers/VideoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGeneration.Contracts.Messaging;
using System.Threading.Tasks;
using UpYourChannel.Data.Models;
using UpYourChannel.Web.Services;
using UpYourChannel.Web.ViewModels.Video;

namespace UpYourChannel.Web.Controllers
{
    public class VideoController : Controller
    {
        private readonly IVideoService videoService;

        public VideoController(IVideoService videoService)
        {
            this.videoService = videoService;
        }

        [Authorize]
        public IActionResult AddVideo()
        {
            return this.View();
        }
        
        //[HttpPost]
        //public async Task<IActionResult> AddVideo(VideoInputModel input, string userId)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return this.View(input);
        //    }
        //    await videoService.AddVideoAsync(input.Link,input.Title,input.Description,userId);
        //    return Redirect("/Video/AllVideos");
        //}

        public IActionResult AllVideos(string search)
        {
            if (string.IsNullOrWhiteSpace(search))
            {
                return this.View(videoService.AllVideos());
            }
            return this.View(videoService.VideosBySearch(search));
        }
    }
}

UpYourChanel.Web/Views/Video/AddVideo.cshtml
@model UpYourChannel.Web.ViewModels.Video.VideoInputModel

<br />
<br />
<br />
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1>Add Your Video:</h1>
            <form asp-controller="RequestedVideo" asp-action="AddRequestedVideo" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control" placeholder="ex: Google" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Link"></label>
                    <input asp-for="Link" class="form-control" placeholder="ex: https://www.google.com/" />
                    <span asp-validation-for="Link" class=" = text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description"></label>
                    <textarea asp-for="Description" rows="7" class="form-control" aria-label="With textarea" placeholder="ex: Google LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, search engine, cloud computing, software, and hardware. It is considered one of the Big Four technology companies, alongside Amazon, Apple, and Microsoft."></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <hr />
                <input type="submit" class="btn btn-primary" value="Add">
                <a class="btn btn-primary float-right" asp-controller="Video" asp-action="AllVideos" role="button">Go to all videos</a>
            </form>
        </div>
        <div class="col-md-6">
            <h1 class="text-center">We look through every video!</h1>
            <br />
            <strong>How to approve your video?</strong>
            <hr />
            <p>1. Make good video that will help someone grow his channel.</p>
            <p>2. Add a valid Link.</p>
            <p>3. Use good Title and Description.</p>
            <strong>We will approve or not your video within 1 hour.</strong>
        </div>
    </div>
</div>

UpYourChanel.Web/Views/Video/AllVideos.cshtml
@using UpYourChannel.Web.ViewModels.Video
@model AllVideosViewModel

<br />
<br />
<br />
<br />

<head>
    <link rel="stylesheet" href="~/css/d.css" />
</head>
<div class="container  text-center ">
    <div class="row">
        <div class="col-sm-4 text-center">
            <div class="text-center bottom-align-text">
                <h2>Feel free to add your video:</h2>
            </div>
        </div>
        <div class="col-sm-4 text-center">
            <div class="text-center">
                <h1 class="display-4">All Videos</h1>
            </div>
        </div>
    </div>
</div>
<br />

@if ((string)TempData["SuccessOnAddVideo"] == "Thanks for adding your video.")
{
    <div class="container">
        <div class="text-center alert alert-success alert-dismissible fade show">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>@TempData["SuccessOnAddVideo"] We will see it under 1 hour.</strong>
        </div>
    </div>
    @*<script>alert("@TempData["SuccessOnAddVideo"]");</script>*@
}
<div class="container text-center">
    <div class="row">
        <div class="col-sm-4 text-center">
            <a asp-controller="Video" asp-action="AddVideo" class="btn btn-primary btn-lg" role="button" aria-pressed="true">Add your Video</a>
        </div>

        <form asp-controller="Video" asp-action="AllVideos" method="get" class="col-md-4 @*form-inline d-flex*@ text-center form-group has-search">
            <span class="fa fa-search form-control-feedback"></span>
            <input name="search" class="form-control" type="text" placeholder="Search"
                   aria-label="Search">
        </form>
    </div>
</div>
<br />

<div class="container">
    <div class="row">
        @foreach (var video in Model.AllVideos)
        {
            <div class="col-sm-4">
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src=@video.IFrameSource allowfullscreen></iframe>
                </div>
                <label text-justify text-dark">@video.Title</label>
            </div>
        }
    </div>
</div>
<br />