UpYourChanel.Web/ViewModels/Post/AllPostsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UpYourChannel.Web.ViewModels.Post
{
    public class AllPostsViewModel
    {
        public List<PostViewModel> Posts { get; set; }
    }
}

UpYourChanel.Web/ViewModels/Post/PostIndexModel.cs
using System.Collections.Generic;
using UpYourChannel.Web.ViewModels.Comment;

namespace UpYourChannel.Web.ViewModels.Post
{
    public class PostIndexModel
    {
        public PostViewModel Post { get; set; }

        public CommentInputModel Comment { get; set; }

        public IEnumerable<CommentViewModel> Top3Comments { get; set; }

        public IEnumerable<CommentViewModel> Top3Answers { get; set; }
    }
}

UpYourChanel.Web/ViewModels/Post/PostInputViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace UpYourChannel.Web.ViewModels.Post
{
    public class PostInputViewModel
    {
        [Required]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        [Required]
        public int Category { get; set; }

        public string UserId { get; set; }
    }
}

UpYourChanel.Web/ViewModels/Post/PostSubjectViewModel.cs
using System.Collections.Generic;

namespace UpYourChannel.Web.ViewModels.Post
{
    public class PostSubjectViewModel
    {
        public int TotalPosts { get; set; }

        // maybe make categories like table
        public Dictionary<string,int> PostForCategories { get; set; }
    }
}

UpYourChanel.Web/ViewModels/Post/PostViewModel.cs
using Ganss.XSS;
using System;
using System.Collections.Generic;
using System.Linq;
using UpYourChannel.Web.ViewModels.Comment;

namespace UpYourChannel.Web.ViewModels.Post
{
    public class PostViewModel
    {
        public int Id { get; set; }

        public DateTime CreatedOn { get; set; }

        public string Title { get; set; }

        public string Content { get; set; }

        public string UserId { get; set; }

        public string UserUserName { get; set; }

        public int VotesCount { get; set; }

        public int CommentsCount => Comments.Count();

        public IEnumerable<CommentViewModel> Comments { get; set; }

        public string SanitizedContent => new HtmlSanitizer().Sanitize(this.Content);

        public string SanitizedContentWith150Symbols => new HtmlSanitizer().Sanitize(this.Content.Substring(0, Math.Min(Content.Length, 1000)));

        public bool IsThisUser { get; set; }

        public string UserProfilePictureUrl { get; set; }
    }
}

UpYourChanel.Web/Controllers/CommentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using UpYourChannel.Data.Models;
using UpYourChannel.Web.Services;
using UpYourChannel.Web.ViewModels.Comment;

namespace UpYourChannel.Web.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService commentService;
        private readonly IPostService postService;
        private readonly IMessageService messageService;
        private readonly UserManager<User> userManager;

        public CommentController(ICommentService commentService, IPostService postService, IMessageService messageService, UserManager<User> userManager)
        {
            this.commentService = commentService;
            this.postService = postService;
            this.messageService = messageService;
            this.userManager = userManager;
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateComment(CommentInputModel input, bool isAnswer)
        {
            var post = await postService.ByIdAsync(input.PostId);
            var user = await userManager.GetUserAsync(this.User);
            await commentService.CreateCommentAsync(input.PostId, user.Id, input.Content, input.ParentId, isAnswer);
            await messageService.AddMessageToUserAsync($"Your post was commented by {user.UserName}", post.UserId, post.Id);
            if (input.ParentId != 0)
            {
                var comment = await commentService.GetCommentByIdAsync(input.ParentId);
                await messageService.AddMessageToUserAsync($"Your comment was commented by {user.UserName}", comment.UserId, post.Id);
            }
            return Redirect($"/Post/ById/{input.PostId}");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditComment(int commentId, string newContent, int postId)
        {
            var userId = this.userManager.GetUserId(this.User);
            if (await commentService.EditCommentAsync(commentId, newContent, userId) == false)
            {
                return NotFound();
            }
            return Redirect($"/Post/ById/{postId}");
        }

        [Authorize]
        public async Task<IActionResult> DeleteComment(int id, int postId)
        {
            var userId = this.userManager.GetUserId(this.User);
            if (await commentService.DeleteCommentByIdAsync(id,postId, userId) == false)
            {
                return NotFound();
            }
            return Redirect($"/Post/ById/{postId}");
        }
    }
}

UpYourChanel.Web/Controllers/PostController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using UpYourChannel.Data.Models;
using UpYourChannel.Web.Paging;
using UpYourChannel.Web.Services;
using UpYourChannel.Web.ViewModels.Comment;
using UpYourChannel.Web.ViewModels.Post;
using AutoMapper.QueryableExtensions;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using System;
using UpYourChannel.Data.Models.Enums;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using System.Collections.Immutable;

namespace UpYourChannel.Web.Controllers
{

    public class PostController : Controller
    {
        private readonly IMapper mapper;
        private readonly IPostService postService;
        private readonly IVoteService voteService;
        private readonly ICommentService commentService;
        private readonly IMessageService messageService;
        private readonly UserManager<User> userManager;

        public PostController(IMapper mapper, IPostService postService, IVoteService voteService, ICommentService commentService,IMessageService messageService, UserManager<User> userManager)
        {
            this.mapper = mapper;
            this.postService = postService;
            this.voteService = voteService;
            this.commentService = commentService;
            this.messageService = messageService;
            this.userManager = userManager;
        }

        [Authorize]
        public IActionResult CreatePost()
        {
            return this.View();
        }
        public async Task<int> OnGetAsync()
        {
            var user = await userManager.Users.Include(x => x.Messages).SingleOrDefaultAsync(x => x.Id == userManager.GetUserId(User));
            return user.Messages.Count();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreatePost(PostInputViewModel input)
        {
            if (!ModelState.IsValid)
            {
                return this.View(input);
            }
            TempData["newPost"] = "Successfully created Post!";
            // maybe remove UserId From input
            input.UserId = userManager.GetUserId(this.User);
            var postId = await postService.CreatePostAsync(input.Title, input.Content, input.UserId, input.Category);
            return Redirect($"/Post/ById/{postId}");
        }

        [Authorize]
        public async Task<IActionResult> EditPost(int postId, int pageNumber)
        {
            TempData["postId"] = postId;
            TempData["pageNumber"] = pageNumber;
            var post = mapper.Map<PostInputViewModel>(await postService.ReturnPostInputModelByIdAsync(postId));
            return View(post);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditPost(PostInputViewModel input, int postId)
        {
            var user = await userManager.GetUserAsync(this.User);
            var isAdmin = await userManager.IsInRoleAsync(user, "Admin");
            if (await postService.EditPostAsync(postId, input.Content, input.Title, user.Id, isAdmin) == false)
            {
                return NotFound();
            }
            return Redirect($"/Post/ById/{postId}");
        }

        [Authorize]
        public async Task<IActionResult> DeletePost(int postId)
        {
            var user = await userManager.GetUserAsync(this.User);
            var isAdmin = await userManager.IsInRoleAsync(user, "Admin");
            if (await postService.DeletePostAsync(postId, user.Id, isAdmin) == false)
            {
                return NotFound();
            }
            return Redirect("/Post/AllPosts");
        }

        [HttpGet]
        public IActionResult AllPosts(int? pageNumber, string category, string sortBy)
        {
            var dbPosts = postService.AllPosts(category, sortBy);
            var configuration = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Comment, CommentViewModel>();
                cfg.CreateMap<Post, PostViewModel>()
                .ForMember(x => x.Comments, y => y.MapFrom(p => p.Comments));
            });
            var allPosts = new AllPostsViewModel()
            {
                Posts = dbPosts.ProjectTo<PostViewModel>(configuration).ToList()
            };
            var userId = userManager.GetUserId(this.User);
            allPosts.Posts.Where(x => x.UserId == userId).ToList().ForEach(x => x.IsThisUser = true);
            var pagination = PaginatedList<PostViewModel>.Create(allPosts.Posts, pageNumber ?? 1, GlobalConstants.PageSize);
            pagination.Category = category;
            pagination.SortBy = sortBy;
            return View(pagination);
        }

        public async Task<IActionResult> ById(int id)
        {
            var userId = userManager.GetUserId(this.User);
            var postViewModel = new PostIndexModel()
            {
                Post = mapper.Map<PostViewModel>(await postService.ByIdAsync(id))
            };
            if (postViewModel == null)
            {
                return this.NotFound();
            }
            if (postViewModel.Post.UserId == userId)
            {
                postViewModel.Post.IsThisUser = true;
            }
            postViewModel.Post.Comments.Where(x => x.UserId == userId).ToList().ForEach(x => x.IsThisUser = true);
            postViewModel.Post.VotesCount = voteService.AllVotesForPost(id);
            postViewModel.Top3Comments = mapper.Map<IEnumerable<CommentViewModel>>(commentService.Top3CommentsForPost(id));
            postViewModel.Top3Answers = mapper.Map<IEnumerable<CommentViewModel>>(commentService.Top3AnswersForPost(id));
            postViewModel.Post.Comments.ToList().ForEach(x => x.VotesCount = voteService.AllVotesForComment(x.Id));
            return this.View(postViewModel);
        }

        [Authorize]
        public IActionResult AddCommentToPost()
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddCommentToPost(PostIndexModel input, bool isAnswer)
        {
            var post = await postService.ByIdAsync(input.Comment.PostId);
            var user = await userManager.GetUserAsync(this.User);
            await commentService.CreateCommentAsync(input.Comment.PostId, user.Id, input.Comment.Content, input.Comment.ParentId, isAnswer);
            await messageService.AddMessageToUserAsync($"Your post was commented by {user.UserName}",post.UserId, post.Id);
            return Redirect($"/Post/ById/{input.Comment.PostId}");
        }

        public async Task<IActionResult> PostSubjects()
        {
            var postSubject = new PostSubjectViewModel()
            {
                TotalPosts = await postService.PostsCountAsync(null),
                PostForCategories = new Dictionary<string, int>()
            };
            foreach (Enum category in Enum.GetValues(typeof(CategoryType)))
            {
                postSubject.PostForCategories[category.ToString()] = await postService.PostsCountAsync(Convert.ToInt32(category));
            }
            return this.View(postSubject);
        }
    }
}

UpYourChanel.Web/Views/Post/AllPosts.cshtml
@using UpYourChannel.Web.ViewModels.Post
@using UpYourChannel.Web.Paging
@model PaginatedList<PostViewModel>
<br />
<br />
<br />
<br />

<div class="container">
    <a class="float-left btn btn-primary btn-sm" asp-controller="Post" asp-action="CreatePost">Add Post</a>
    <h1 class="display-4 text-center"> All Posts</h1>
    <form asp-controller="Post" asp-action="AllPosts" method="get">
        <input type="hidden" name="category" value="@Model.Category" />
        <select asp-for="@Model.SortBy" onchange="this.form.submit()">
            @*make text infront of every option*@
            <option value="" disabled selected hidden>Sort by:</option>
            <option value="Recent">Recent</option>
            <option value="Popular">Popular</option>
        </select>
    </form>
    <br />
    <br />
    @foreach (var post in Model)
    {
<div class="media-body">
    <h4 class="media-heading"><a asp-controller="Post" asp-action="ById" asp-route-id="@post.Id">@post.Title</a></h4>
    <p>
        @Html.Raw(post.SanitizedContentWith150Symbols + "...")
    </p>
    <ul class="list-inline list-unstyled text-left">
        <li class="list-inline-item">
            <i class="fas fa-user-edit"></i> @post.UserUserName
        </li>
        <li class="list-inline-item">
            <i class="far fa-calendar"></i> @post.CreatedOn
        </li>
        <li class="list-inline-item">
            <i class="fas fa-comments"></i> @post.CommentsCount
        </li>
        <li class="list-inline-item">
            <i class="fas fa-thumbs-up"></i> @post.VotesCount
        </li>
        @if (post.IsThisUser == true || User.IsInRole("Admin"))
        {
            <li class="list-inline-item">
                <a asp-controller="Post" asp-action="EditPost" asp-route-postId="@post.Id">
                    Edit
                </a>
            </li>
            <li class="list-inline-item">
                <a class="text-danger" asp-controller="Post" asp-action="DeletePost" asp-route-postId="@post.Id">Delete</a>
            </li>
        }
    </ul>
</div>
    }
</div>
<br />
<br />
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<div class="text-center">
    <a asp-area="" asp-controller="Post" asp-action="AllPosts" asp-route-category=@Model.Category
       asp-route-pageNumber="@(Model.PageIndex - 1)" asp-route-sortBy=@Model.SortBy
       class="btn btn-default page-item  @prevDisabled">
        Previous
    </a>
    @for (int i = 1; i <= Model.TotalPages; i++)
    {
        <a asp-area="" asp-controller="Post" asp-action="AllPosts" asp-route-category=@Model.Category
           asp-route-pageNumber="@(i)" asp-route-sortBy=@Model.SortBy
           class="btn btn-default">
            @i
        </a>
    }
    <a asp-area="" asp-controller="Post" asp-action="AllPosts" asp-route-category=@Model.Category
       asp-route-pageNumber="@(Model.PageIndex + 1)" asp-route-sortBy=@Model.SortBy
       class="btn btn-default @nextDisabled">
        Next
    </a>
</div>

UpYourChanel.Web/Views/Post/ById.cshtml
@model UpYourChannel.Web.ViewModels.Post.PostIndexModel
@{
    this.ViewData["Title"] = Model.Post.Title;

    async Task DisplayComments(int? parentId)
    {
        var comments = this.Model.Post.Comments.Where(x => x.ParentId == parentId);
        if (!comments.Any())
        {
            return;
        }

        @foreach (var comment in comments)
        {
            var isAnswer = comment.IsAnswer ? "<i class=\"fas fa-star\"></i>Answer" : "";
            var id = "v" + comment.Id;
            var editComment = "e" + comment.Id;
            <div class="container-fluid mt-100">
                <div class="row">
                    <div class="col-md-12">
                        @*<div class="card mb-4">
                            <div class="card-header">*@
                        <div class="media flex-wrap w-100 ml-4">
                            <img src="@comment.UserProfilePictureUrl" class="d-block rounded-circle" style="border-radius:50%; width:50px; height:50px">
                            <div class="media-body ml-3">
                                <div>
                                    <strong class="text-danger">@Html.Raw(isAnswer)</strong>
                                </div>
                                <strong class="mt-0 text-primary">@comment.UserUserName</strong>
                                <div class="mt-0 text-muted small">@comment.CreatedOn.ToString()</div>

                                @Html.Raw(comment.SanitizedContent)
                                <div class="text-muted ">
                                    <a href="javascript:void(0)" onclick="sendVoteForComment(@comment.Id, true)">
                                        <i class="fa fa-thumbs-up"></i>
                                    </a>
                                    <a id=@id>@comment.VotesCount</a>
                                    <a href="javascript:void(0)" onclick="sendVoteForComment(@comment.Id, false)">
                                        <i class="fa fa-thumbs-down"></i>
                                    </a>
                                    <a href="javascript:void(0)" onclick="showAddComment(@comment.Id)">reply</a>
                                    @if (comment.IsThisUser == true)
                                    {
                                        <a href="javascript:void(0)" onclick="showEditComment(@comment.Id)">edit</a>
                                        <a class="text-danger"
                                           asp-controller="Comment" asp-action="DeleteComment"
                                           asp-route-id="@comment.Id" asp-route-postId="@Model.Post.Id">delete</a>
                                    }
                                    <div id="@editComment" style="display : none">
                                        <hr />
                                        <form asp-controller="Comment" asp-action="EditComment" method="post">
                                            <input type="hidden" name="postId" value="@Model.Post.Id" />
                                            <input type="hidden" name="commentId" value="@comment.Id" />
                                            <textarea class="someTextBox form-control" name="newContent" rows="2" style="width:50%" ; aria-label="With textarea" placeholder="comment..."></textarea>
                                            <div>
                                                <a href="#" onclick="$(this).closest('form').submit()">edit comment</a>
                                            </div>
                                        </form>
                                    </div>
                                    <div id="@comment.Id" style="display : none">
                                        <hr />
                                        <form asp-controller="Comment" asp-action="CreateComment" method="post">
                                            <input type="hidden" name="PostId" value="@Model.Post.Id" />
                                            <input type="hidden" name="ParentId" value="@comment.Id" />
                                            <input type="hidden" name="isAnswer" value="false" />
                                            <textarea class="someTextBox form-control" name="Content" rows="2" style="width:50%" ; aria-label="With textarea" placeholder="comment..."></textarea>
                                            <div>
                                                <a href="#" onclick="$(this).closest('form').submit()">add comment</a>
                                            </div>
                                        </form>
                                        @*<partial name="_CreateCommentPartial" model="new UpYourChannel.Web.ViewModels.Comment.CommentInputModel
                                            { ParentId = comment.Id, PostId = Model.Post.Id }" />*@
                                    </div>
                                </div>

                            </div>
                        </div>
                        <hr />
                        <div class="card-body">
                            @{ await DisplayComments(comment.Id); }
                        </div>
                    </div>
                </div>
            </div>
        }
    }
}
<head>
    <link href="~/css/comments.css" rel="stylesheet">
    <script src="/lib/tinymce/tinymce.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: "textarea.tinyMce",
            plugins: [
                "image paste table link code media"
            ]
        });
    </script>
</head>
<br />
<br />
<br />
<br />
<h1 class="text-center">@Model.Post.Title</h1>
<br />
@if ((string)TempData["newPost"] == "Successfully created Post!")
{
    <div class="container">
        <div class="text-center alert alert-success alert-dismissible fade show">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>@TempData["newPost"]</strong>
        </div>
    </div>
    @*<script>alert("@TempData["SuccessOnAddVideo"]");</script>*@
}
<div class="container">
    <!-- maybe container-fluid -->
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-4">
                <div class="card-header">
                    <div class="media flex-wrap w-100 align-items-center">
                        <img src=@Model.Post.UserProfilePictureUrl class="d-block rounded-circle" style="border-radius:50%; width:70px; height:70px">
                        <div class="media-body ml-3">
                            <strong class="text-primary">@Model.Post.UserUserName</strong>
                            <div class="text-muted small">@Model.Post.CreatedOn</div>
                            @if (Model.Post.IsThisUser == true)
                            {
                                <a asp-controller="Post" asp-action="EditPost" asp-route-postId="@Model.Post.Id">Edit</a>
                                <a class="text-danger" asp-controller="Post" asp-action="DeletePost" asp-route-postId="@Model.Post.Id">Delete</a>
                            }
                        </div>
                        <div class="text-muted ml-3">
                            <form id="votesForm" method="post"></form>
                            <div>
                                <a href="javascript:void(0)" onclick="sendVote(@Model.Post.Id, true)">
                                    <i class="fa fa-thumbs-up"></i>
                                </a>
                            </div>
                            <div id="votesCount">@Model.Post.VotesCount</div>
                            <div>
                                <a href="javascript:void(0)" onclick="sendVote(@Model.Post.Id, false)">
                                    <i class="fa fa-thumbs-down"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @Html.Raw(Model.Post.SanitizedContent)
                </div>
                <div class="card-footer flex-wrap align-items-center px-0 pt-0 pb-3">
                    <form asp-controller="Post" asp-action="AddCommentToPost" method="post">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="px-4 pt-3 form-inline">
                            <input type="hidden" name="Comment.PostId" value="@Model.Post.Id">
                            <textarea required asp-for="Comment.Content" rows="2" cols="70" class="form-control" aria-label="With textarea" placeholder="Comment..."></textarea>
                            <div class="px-4 "> <button type="submit" class="btn btn-primary">Comment &nbsp;<i class="far fa-comment-dots"></i></button> </div>
                            <div class="px-4 "> <button type="button" class="btn btn-primary" onclick="showAddCommentForm()">Answer &nbsp;<i class="far fa-comment-dots"></i></button> </div>
                        </div>
                    </form>
                    <br />
                    @{ await DisplayComments(null); }
                </div>
            </div>
        </div>
    </div>
</div>
<br />
<br />
<div class="container">
    <form asp-controller="Post" asp-action="AddCommentToPost" method="post" id="AddCommentForm" style="display: none">
        <input type="hidden" name="Comment.PostId" value="@Model.Post.Id" />
        <input type="hidden" name="isAnswer" value="true" />
        <div>
            <label for="Content"></label>
            <textarea asp-for="Comment.Content" class="tinyMce form-control"></textarea>
        </div>
        <div>
            <input type="submit" class="btn btn-primary" value="Add answer" />
        </div>
    </form>
</div>
<div class="container">
    <h1 class="text-center">Top 3</h1>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <h1 class="text-center">Answers</h1>
            <br />
            @{
                var count = 1;
                foreach (var answer in Model.Top3Answers)
                {

                    <div>
                        <strong>Number @count best answer</strong>
                        <br />
                        <div>@Html.Raw(answer.SanitizedContent)</div>
                    </div>
                    <hr />
                    count++;
                }
            }
        </div>
        <div class="col-md-6">
            <h1 class="text-center">Comments</h1>
            <br />
            @{
                var count2 = 1;
                foreach (var comment in Model.Top3Comments)
                {

                    <div>
                        <strong>Number @count2 best comment</strong>
                        <br />
                        <div>@Html.Raw(comment.SanitizedContent)</div>
                    </div>
                    <hr />
                    count2++;
                }
            }
        </div>
    </div>
</div>
@section Scripts {
    <script>

        function showAddComment(commentId) {
            $("#" + commentId).toggle();
        }

        function showEditComment(commentId) {
            $('#e' + commentId).toggle();
        }

        function showAddCommentForm() {
            $("#AddCommentForm").show();
            $([document.documentElement, document.body]).animate({
                scrollTop: $("#AddCommentForm").offset().top
            }, 1000);
        }

        function sendVote(postId, isUpVote) {
            var token = $("#votesForm input[name=__RequestVerificationToken]").val();
            var json = { postId: postId, isUpVote: isUpVote };
            $.ajax({
                url: "/api/VoteApi/VoteForPost",
                type: "POST",
                data: JSON.stringify(json),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                headers: { 'X-CSRF-TOKEN': token },
                success: function (data) {
                    $("#votesCount").html(data.votesCount);
                }
            });
        }

        function sendVoteForComment(postId, isUpVote) {
            var token = $("#votesForm input[name=__RequestVerificationToken]").val();
            var json = { postId: postId, isUpVote: isUpVote };
            $.ajax({
                url: "/api/VoteApi/VoteForComment",
                type: "POST",
                data: JSON.stringify(json),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                headers: { 'X-CSRF-TOKEN': token },
                success: function (data) {
                    $("#v" + postId).html(data.votesCount);
                }
            });
        }
    </script>
}

UpYourChanel.Web/Views/Post/CreatePost.cshtml
@using UpYourChannel.Data.Models.Enums
@model UpYourChannel.Web.ViewModels.Post.PostInputViewModel

<br />
<br />
<br />
<br />
<script src="/lib/tinymce/tinymce.min.js" type="text/javascript"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea",
        plugins: [
            "image paste table link code media"
        ]
    });
</script>
<div class="container">
    <h1>Add your post:</h1>
    <form asp-controller="Post" asp-action="CreatePost" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="btn-group">
        </div>
        <div class="form-group md-f">
            <label asp-for="Title">Title:</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Content">Content:</label>
            <textarea asp-for="Content" rows="10" class="form-control" aria-label="With textarea"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
        <div class="form-group">
            <select class="form-control" required
                    asp-for="Category">
                <option value="" disabled selected hidden>Category:</option>
                <option value="1">General Discussions</option>
                <option value="2">Introduction</option>
            </select>
            <span asp-validation-for="Category" class="text-danger"></span>
        </div>
            <hr />
            <input type="submit" class="btn btn-primary" value="Post">
            <a class="float-right btn btn-primary" asp-controller="Post" asp-action="PostSubjects">Back to Forum</a>
    </form>
</div>

UpYourChanel.Web/Views/Post/EditPost.cshtml
@model UpYourChannel.Web.ViewModels.Post.PostInputViewModel

<br />
<br />
<br />
<br />
<script src="/lib/tinymce/tinymce.min.js" type="text/javascript"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea",
        plugins: [
            "image paste table link code media"
        ]
    });
</script>
<div class="container">
    <h1>Edit your post:</h1>
    <form asp-controller="Post" asp-action="EditPost" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <input type="hidden" name="postId" value="@TempData["postId"]">
        <input type="hidden" name="pageNumber" value="@TempData["pageNumber"]"> 
        <div class="form-group md-f">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Content"></label>
            <textarea asp-for="Content" rows="10" class="form-control" aria-label="With textarea"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>

        <hr />
        <input type="submit" class="btn btn-primary" value="Edit">
    </form>
</div>